services:
  - type: web
    name: cybershield
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libzbar0
      pip install -r requirements.txt
    startCommand: gunicorn app:app